import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cpSync, mkdirSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";

/** 需要复制到 dist/ 的部署文件 */
const DIST_FILES = ["main.js", "manifest.json", "styles.css"];

/** 构建完成后将部署文件复制到 dist/ 目录 */
function copyToDist() {
	mkdirSync("dist", { recursive: true });
	for (const file of DIST_FILES) {
		try {
			cpSync(file, `dist/${file}`);
		} catch {
			// styles.css 等文件可能不存在，静默跳过
		}
	}
	console.log(`Copied to dist/: ${DIST_FILES.join(", ")}`);
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// Transformers.js 可选原生依赖（Obsidian/Electron 环境不需要）
		"onnxruntime-node",
		"sharp",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// Transformers.js 在 ESM 中使用 import.meta.url，CJS 环境下需要兜底
	define: {
		"import.meta.url": JSON.stringify("file:///"),
	},
});

if (prod) {
	await context.rebuild();
	copyToDist();
	process.exit(0);
} else {
	await context.watch();
}
