import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cpSync, mkdirSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";

const buildOptions = {
	banner: { js: banner },
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	entryPoints: ["src/main.ts"],
	format: "cjs",
	logLevel: "info",
	minify: prod,
	outfile: "main.js",
	sourcemap: prod ? false : "inline",
	target: "es2020",
	treeShaking: true,
};

const DIST_FILES = ["main.js", "manifest.json", "styles.css"];

function copyToDist() {
	mkdirSync("dist", { recursive: true });
	for (const file of DIST_FILES) {
		try {
			cpSync(file, `dist/${file}`);
		} catch {
			// Ignore optional files such as styles.css when they do not exist.
		}
	}
	console.log(`Copied to dist/: ${DIST_FILES.join(", ")}`);
}

if (prod) {
	await esbuild.build(buildOptions);
	copyToDist();
	process.exit(0);
} else {
	const context = await esbuild.context(buildOptions);
	await context.watch();
}
